### ISSUE TITLE
[Feature] Use Makefile

### ISSUE THREAD

**Issue by abhishekkumar2718** [harshagrwl/CSV-Data-Sorting#1]
Building the application through a makefile will be more efficient and easier for the end-users. You can read more about makefiles [here](https://opensource.com/article/18/8/what-how-makefile) and [here](http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/)

I would love to work on this if offered.

**Comment by harshagrwl** [comment]
Sure, Please go ahead and let me know if you need any help.

**Comment by abhishekkumar2718** [comment]
I couldn't push my branch. Could you add push access for me or add me as a contributor?

- Going through source code, there was no use of `nonthreadedserver.c`.
- `mergesort.c` needs a header file.
- Code style can be improved a lot.

There can be a lot of work done on this, depending on how serious you are about this project.

**Comment by harshagrwl** [comment]
I've added you as a contributor.
- ```mergesort.c``` and ``nonthreadedserver.c``` were written initially but their code was refactored and added to other files.
- The Code has many comments and the styling is a bit inconsisitent. The project was completed in a hurry due to evaluation deadlines. That's why i was not able to fix these things.
- It would be great if you can possibly create issues highlighting the changes that need to be done.

**Comment by harshagrwl** [comment]
The code is not compiled by running the makefile. It shows some errors.
![Screenshot from 2019-11-17 14-43-06](https://user-images.githubusercontent.com/43218240/69005459-b22fe500-0948-11ea-92bf-8a2e9a275ab4.png)

**Comment by abhishekkumar2718** [comment]
Fixed this.
